spring.application.name=attendance-management-system

spring.config.import=optional:file:./attendence-management-system/src/.env[.properties],optional:file:./src/.env[.properties]


spring.datasource.url=${DATA_SOURCE_URL}
spring.datasource.username=${DATA_USERNAME}
spring.datasource.password=${DATA_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Google OAuth2 Client Configuration
spring.security.oauth2.client.registration.google.client-id=${OAUTH_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${OAUTH_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=profile, email
spring.jpa.properties.hibernate.format_sql=true
